Langley Wireframe Geometry Library: svm.c File Reference
svm.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <math.h>
#include "svm.h"
Functions
void matrix44d_identity (Matrix44d m44)
void matrix44d_write (FILE *fptr, Matrix44d m44)
void matrix44d_set_translate (Matrix44d m44, double tx, double ty, double tz)
void matrix44d_set_scale (Matrix44d m44, double xscale, double yscale, double zscale)
void matrix44d_xrotation_radians (Matrix44d m44, double phi)
void matrix44d_yrotation_radians (Matrix44d m44, double theta)
void matrix44d_zrotation_radians (Matrix44d m44, double psi)
void matrix44d_mm (Matrix44d a44, Matrix44d b44, Matrix44d c44)
void matrix44d_mv (Matrix44d m44, Vector3d pin, Vector3d pout)
Function Documentation
matrix44d_identity()
void matrix44d_identity (Matrix44d m44)
Referenced by matrix44d_xrotation_radians(), matrix44d_yrotation_radians(), matrix44d_zrotation_radians(), wgs_object_new(), and wgs_object_transform().
matrix44d_mm()
void matrix44d_mm (Matrix44d a44, Matrix44d b44, Matrix44d c44)
Referenced by wgs_object_read().
matrix44d_mv()
void matrix44d_mv (Matrix44d m44, Vector3d pin, Vector3d pout)
Referenced by wgs_object_transform().
matrix44d_set_scale()
void matrix44d_set_scale (Matrix44d m44, double xscale, double yscale, double zscale)
Referenced by wgs_object_read().
matrix44d_set_translate()
void matrix44d_set_translate (Matrix44d m44, double tx, double ty, double tz)
Referenced by wgs_object_read().
matrix44d_write()
void matrix44d_write (FILE * fptr, Matrix44d m44)
matrix44d_xrotation_radians()
void matrix44d_xrotation_radians (Matrix44d m44, double phi)
References matrix44d_identity().
Referenced by wgs_object_read().
matrix44d_yrotation_radians()
void matrix44d_yrotation_radians (Matrix44d m44, double theta)
References matrix44d_identity().
Referenced by wgs_object_read().
matrix44d_zrotation_radians()
void matrix44d_zrotation_radians (Matrix44d m44, double psi)
References matrix44d_identity().
Referenced by wgs_object_read().