Langley Wireframe Geometry Library: wgs.c File Reference
wgs.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <math.h>
#include "wgs.h"
Macros
#define TRUE 1
#define FALSE 0
#define MAX(a, b) (a)>(b) ? (a) : (b)
#define M_PI 3.1412592653589793238462643383
Functions
void wgs_read_name (FILE *fptr, char *name)
wgsWireframe * wgs_wireframe_new ()
void wgs_wireframe_free (wgsWireframe *wf)
wgsWireframe * wgs_wireframe_read (FILE *fptr)
wgsObject * wgs_object_new ()
wgsObject * wgs_object_copy (wgsObject *obj, int id)
void wgs_object_free (wgsObject *object)
Vector3d * wgs_object_allocate (int nline, int npnt)
Vector3d * wgs_object_reallocate (Vector3d *p, int nline, int npnt)
wgsObject * wgs_object_read (FILE *fptr)
wgsObject * wgs_object_reflect (wgsObject *obj, int id)
int wgs_object_needs_transform (wgsObject *obj)
void wgs_object_transform (wgsObject *obj)
void wgs_wireframe_convert_to_global (wgsWireframe *wf)
Macro Definition Documentation
FALSE
#define FALSE 0
Referenced by wgs_object_needs_transform(), wgs_read_name(), and wgs_wireframe_read().
M_PI
#define M_PI 3.1412592653589793238462643383
Referenced by wgs_object_read().
MAX
#define MAX (a, b) (a)>(b) ? (a) : (b)
Referenced by wgs_wireframe_read().
TRUE
#define TRUE 1
Referenced by wgs_object_needs_transform(), wgs_read_name(), and wgs_wireframe_read().
Function Documentation
wgs_object_allocate()
Vector3d* wgs_object_allocate (int nline, int npnt)
Referenced by wgs_object_read().
wgs_object_copy()
wgsObject* wgs_object_copy (wgsObject * obj, int id)
References wgs_object_free(), and wgs_object_new().
Referenced by wgs_object_reflect().
wgs_object_free()
void wgs_object_free (wgsObject * object)
Referenced by wgs_object_copy(), wgs_object_read(), and wgs_wireframe_free().
wgs_object_needs_transform()
int wgs_object_needs_transform (wgsObject * obj)
References FALSE, and TRUE.
Referenced by wgs_object_transform().
wgs_object_new()
wgsObject* wgs_object_new ()
References matrix44d_identity().
Referenced by wgs_object_copy(), and wgs_object_read().
wgs_object_read()
wgsObject* wgs_object_read (FILE * fptr)
References M_PI, matrix44d_mm(), matrix44d_set_scale(), matrix44d_set_translate(), matrix44d_xrotation_radians(), matrix44d_yrotation_radians(), matrix44d_zrotation_radians(), wgs_object_allocate(), wgs_object_free(), wgs_object_new(), and wgs_read_name().
Referenced by wgs_wireframe_read().
wgs_object_reallocate()
Vector3d* wgs_object_reallocate (Vector3d * p, int nline, int npnt)
wgs_object_reflect()
wgsObject* wgs_object_reflect (wgsObject * obj, int id)
References wgs_object_copy().
Referenced by wgs_wireframe_convert_to_global().
wgs_object_transform()
void wgs_object_transform (wgsObject * obj)
References matrix44d_identity(), matrix44d_mv(), and wgs_object_needs_transform().
Referenced by wgs_wireframe_convert_to_global().
wgs_read_name()
void wgs_read_name (FILE * fptr, char * name)
References FALSE, and TRUE.
Referenced by wgs_object_read(), and wgs_wireframe_read().
wgs_wireframe_convert_to_global()
void wgs_wireframe_convert_to_global (wgsWireframe * wf)
References wgs_object_reflect(), and wgs_object_transform().
wgs_wireframe_free()
void wgs_wireframe_free (wgsWireframe * wf)
References wgs_object_free().
wgs_wireframe_new()
wgsWireframe* wgs_wireframe_new ()
Referenced by wgs_wireframe_read().
wgs_wireframe_read()
wgsWireframe* wgs_wireframe_read (FILE * fptr)
References FALSE, MAX, TRUE, wgs_object_read(), wgs_read_name(), and wgs_wireframe_new().